config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "leads#index"
  
  resources :leads do
    member do 
      post :update_status
    end
    collection do
      post :search
    end
  end
  
  resources :activities do
    member do
      post :render_update_modal
      post :render_delete_modal
    end
  end

  get 'health', to: 'health#show'
end

app/models/activity.rb
# delete later
class Activity 
  include ActiveModel::Model

  attr_accessor :id, :status, :due_date, :description
  def initialize id, status, due_date, description
    @id = id
    @status = status
    @due_date = due_date
    @description = description
  end

  def to_key
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
# delete later
class Lead 
  include ActiveModel::Model

  attr_accessor :id, :company_name, :email, :phone, :status, :contact_name, :address, :description
  def initialize id, company_name, email, phone, status, contact_name
    @id = id
    @company_name = company_name
    @email = email
    @phone = phone
    @status = status
    @contact_name = contact_name
    @address = "dummy address"
    @description = "dummy description"
  end

  def to_key
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :inject_data

  def show
    @total_pages = 4
    @current_pages = 1
    render partial: 'activities/lists'
  end

  def new
  end

  def create
    params[:status] || "false" #checkbox ngirimny bentuk string
    params[:due_date] || nil
    params[:description] || nil

    if params[:status].present? #temporary, later change to if model.save
      redirect_to lead_path(params[:lead_id])
    end
  end

  def update
    render json: {id: 1, status: "true", due_date: Time.now, description: "Random Cat"}
  end

  def destroy
    redirect_to lead_path(params[:lead_id])
  end

  def render_update_modal
    @activity = Activity.new(2, true, Time.now(), "Random desc")
    render :partial => 'popup_update_activity'
  end

  def render_delete_modal
    @activity = Activity.new(2, true, Time.now(), "Random desc")
    render :partial => 'helpers/popup_delete', locals: {popup_id: "popup-delete-activity",delete_url: activity_path(params[:id], lead_id: params[:lead_id]), prompt_delete: t("activity.prompt-delete")}
  end

  def inject_data
    @lists = [
        Lead.new(1, SecureRandom.base64(8), "email a", "081222", "new lead", "Budi"), 
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi")]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/health_controller.rb
class HealthController < ApplicationController
 def show
   render :html => "I'm totally healthy"
 end 
end 

app/controllers/leads_controller.rb
require "#{Rails.root}/lib/domain/leads/leads"

class LeadsController < ApplicationController
  before_action :init_repo_queries

  def index
    @first_page = 1
    @last_page = 10
    @industry_lists = [["Retail/Online Shop", 1], ["Jasa", 2], ["Konstruksi", 2]]
  end

  def create
    render :partial => 'lists'
  end

  def show
    @industry_lists = [["Retail/Online Shop", 1], ["Jasa", 2], ["Konstruksi", 2]]
    @lists = @query_results.take(4)
    @total_pages = 4
    @lead = Lead.new(1, SecureRandom.base64(8), ["email a", "email b"], "081222", "new lead", "Sakura")
    @query_results = [
        Lead.new(1, SecureRandom.base64(8), ["email a", "email b"], "081222", "new lead", "Budi"), 
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), ["email a", "email b"], "081222", "closed", "Budi"),
        Lead.new(4, "hello there", ["email a", "email b"], "081333", "new lead", "Budi")]
  end

  def update
  end

  def destroy
    redirect_to leads_path
  end

  def search
    @query_results = @query_results.sort_by{|x| -x.company_name.downcase}
    
    render :partial => 'lists'
  end

  def update_status
    params[:id] # lead = Lead.find(params[:id])
    params[:lead_status_id] # update lead status with this
    redirect_to lead_path(params[:id])
  end

  def init_repo_queries

    dummy_data = Leads::Lead.new(1,"Maju Mundur Kena","a@b.com","+201241484","Anu", "Itu")

    #@leads_status = [{key: 'value', key: 'value'}, [{key: 'value', key: 'value'}, [{key: 'value', key: 'value'}]]]
    # jadi kl mw dgroup navigasiny kasi array isiny:  [ {hash nav parent}, [ {hashes of nav children} ]]
    @leads_status_filter = [{id: 1, name: "All", count: 23}, 
                      {id: 2, name: "New Leads", count: 4},
                      {id: 3, name: "In Progress", count: 5},
                      [{name: "Closed"}, 
                        [{id: 5, name: "Won", count: 6},
                          {id: 6, name: "Lost", count: 1},
                          {id: 7, name: "Junk", count: 2},
                          {id: 8, name: "Unreachable", count: 0},
                          {id: 9, name: "Underqualified", count: 11},
                          {id: 10, name: "Void/Duplicate", count: 2},
                          {id: 11, name: "Product/Feature", count: 3}]]]

    @leads_status = [["new lead", "new lead"], ["closed", "closed"], ["in progress", "in progress"], ["won", "won"]]

    @query_results = [
        Lead.new(1, SecureRandom.base64(8), "email a", "081222", "new lead", "Budi"), 
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(2, SecureRandom.base64(8), "email b", "081222", "closed", "Budi"),
        Lead.new(3, SecureRandom.base64(8), "email c", "081222", "closed", "Budi"),
        Lead.new(4, "hello there", "email a", "081333", "new lead", "Budi")]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_lists.html.haml
- @lists.each do |i|
  %tr(data-activity-id="#{i.id}")
    %td{style: "width:25%;"}
      = i.company_name
    %td.activity-desc
      = i.company_name
    %td
      .text-right.font-12.flex.justify-content-flex-end
        .margin-right-10
          .status-color.grey
          .grey
            = i.contact_name
        .dropdown.pull-right
          #dropdown-action.dropdown-toggle(data-toggle="dropdown")
            %span.glyphicon.glyphicon-option-vertical.font-20.grey
          %ul.dropdown-menu.dropdown-menu-right
            %li.dropdown-item
              = form_for(i, url: render_update_modal_activity_path(i.id), method: :post, remote: :true, html: {class: "form-render-update-modal-activity"}) do
                = hidden_field_tag :authenticity_token, form_authenticity_token
                = button_tag t("btn.update"), class: "dropdown-menu-link"
            %li.dropdown-item
              = form_for(i, url: render_delete_modal_activity_path(i.id, lead_id: params[:id]), method: :post, remote: :true, html: {class: "form-render-delete-modal-activity"}) do
                = hidden_field_tag :authenticity_token, form_authenticity_token
                = button_tag t("btn.delete"), class: "dropdown-menu-link"

.target-form-render-update-modal-activity
.target-form-render-delete-modal-activity

app/views/activities/_popup_new_activity.html.haml
#popup-new-activity.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("activity.create")
      .modal-body
        = form_tag(activities_path, method: :post, remote: :true, class: "custom-form", id: "form-create-activity") do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          = hidden_field_tag :lead_id, params[:id]
          .row
            .col-xs-6
              = label_tag :status
              .padding-left-5
                %label.switch
                  = check_box_tag :status, true, false, id: 'input-toggle'
                  %span.slider.round
                  %span.closed
                    Closed
                  %span.active
                    Open
            .col-xs-6#target-toggle
              = label_tag :due_date
              .form-group.has-feedback.left
                = text_field_tag :due_date, nil, class: "form-control", "data-provide": "datepicker", disabled: true
                %span.glyphicon.glyphicon-calendar.form-control-feedback.left
          .row.margin-top-10
            .col-xs-12
              = label_tag :description
              = text_field_tag :description, nil, class: "form-control"
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        %button.btn.btn-green.min-width-100{form: "form-create-activity", type: "submit"}
          = t("btn.create")

app/views/activities/_popup_update_activity.html.haml
#popup-update-activity.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("activity.update")
      .modal-body
        - if @activity.present?
          = form_for(@activity, url: activity_path, method: :patch, remote: :true, html: {class: "custom-form", id: "form-update-activity"}) do
            = hidden_field_tag :authenticity_token, form_authenticity_token
            = hidden_field_tag :lead_id, params[:id]
            .row
              .col-xs-6
                = label_tag :status
                .padding-left-5
                  %label.switch
                    = check_box_tag :status, true, @activity.status, id: 'input-toggle'
                    %span.slider.round
                    %span.closed
                      Closed
                    %span.active
                      Open
              .col-xs-6#target-toggle
                = label_tag :due_date
                .form-group.has-feedback.left
                  = text_field_tag :due_date, nil, class: "form-control", "data-provide": "datepicker", disabled: true, value: @activity.due_date
                  %span.glyphicon.glyphicon-calendar.form-control-feedback.left
            .row.margin-top-10
              .col-xs-12
                = label_tag :description
                = text_field_tag :description, nil, class: "form-control", value: @activity.description
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        %button.btn.btn-green.min-width-100{form: "form-update-activity", type: "submit"}
          = t("btn.update")

app/views/helpers/_filter_box.html.haml
.col-xs-12.col-sm-3.filter-box.height-inherit-on-large
  .title-row.margin-bottom-15
    = title
  = form_tag(search_url, method: :post, remote: :true, id: "form-search") do
    = hidden_field_tag :authenticity_token, form_authenticity_token
    .row
      .form-group.has-feedback.left
        = text_field_tag :q, nil, class: "form-control search-input", placeholder: t("form.search-placeholder")
        %span.glyphicon.glyphicon-search.form-control-feedback.left
    .form-group
      - if choices.present?
        - choices.each_with_index do |choice, index|
          - value_checked = index == 0 ? true : false
          - if choice.kind_of?(Array)
            .filter-row.filter-row-parent(data-toggle="collapse" href="#collapseFilter" aria-expanded="false")
              = choice[0][:name]
            .collapse.filter-row-collapse#collapseFilter
              - choice[1].each_with_index do |c, index|
                .filter-row
                  = radio_button_tag :choice, c[:id], value_checked, onclick: '$("#form-search").submit()', id: "choice_nested_#{c[:id]}"
                  = label_tag "choice_nested_#{c[:id]}", "#{c[:name]}".html_safe
          - else
            .filter-row
              = radio_button_tag :choice, choice[:id], value_checked, onclick: '$("#form-search").submit()'
              = label_tag "choice_#{choice[:id]}", "#{choice[:name]}<span>#{choice[:count]}</span>".html_safe
    = hidden_field_tag :search_sort, "desc"
    = hidden_field_tag :page_no, id: "page_no"

app/views/helpers/_pagination.html.haml
.text-right.table-pagination
  = link_to '<<', '#', class: "go-page", "data-value": first_page
  = link_to '<', '#', class: "go-page", "data-value": 1
  Page
  %input#page-value{value: 1}
  = link_to 'Go', '#', class: "go-page", "data-value": 0
  = link_to '>>', '#', class: "go-page", "data-value": last_page
  = link_to '>', '#', class: "go-page", "data-value": 1

app/views/helpers/_popup_delete.html.haml
.modal.fade.custom-modal{id: "#{popup_id}"}
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("form.delete-confirmation")
      .modal-body
        = prompt_delete
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        = link_to t("btn.delete"), delete_url, method: :delete, remote: :true, class: "btn btn-red min-width-100", "data-dismiss" => "modal"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CrmPartner
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('icons/jurnal-icon.png')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :scripts
  %body
    %header
      %nav
        %ul
          %li.nav-border
            = image_tag "icons/jurnal-icon.png"
          %li
            = link_to (image_tag "https://s3-ap-southeast-1.amazonaws.com/jurnal-quickbook-s3/images/icon_apps.svg"), leads_path, title: t("leads.tooltip"), "data-toggle": "tooltip", "data-placement": "right"
    = yield

app/views/leads/_lists.html.haml
- @query_results.each do |r|
  %tr
    %td
      = link_to r.company_name, lead_path(r.id)
    %td
      = r.email
    %td
      = r.phone
    %td
      = r.status

app/views/leads/_popup_new_lead.html.haml
#popup-new-lead.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("leads.create")
      .modal-body
        = form_tag(leads_path, method: :post, remote: :true, class: "custom-form", id: "form-create-lead") do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-xs-12
              .form-group
                = label_tag :company_name, t("leads.company-name", required: "*")
                = text_field_tag :company_name, nil, class: "form-control", required: true
              .form-group
                = label_tag :contact_name, t("leads.contact-name")
                = text_field_tag :contact, nil, class: "form-control"
              .form-group
                = label_tag :phone_number, t("leads.phone")
                = text_field_tag :phone, nil, class: "form-control", pattern: "\\+?[\\s\\d]+", title: t("leads.phone-format")
              .form-group
                = label_tag :email_address, t("leads.email")
                = select_tag :email, [], class: "form-control select2-tags", multiple: true
              .form-group.use-caret
                = label_tag :industry, t("leads.industry", required: "*")
                = select_tag :industry_id, options_for_select(@industry_lists), class: "form-control select2-option", required: true
              .form-group
                = label_tag :address, t("leads.address")
                = text_field_tag :address, nil, class: "form-control"
              .form-group
                = label_tag :descriptions, t("leads.desc")
                = text_field_tag :descriptions, nil, class: "form-control"
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        %button.btn.btn-green.min-width-100{form: "form-create-lead", type: "submit"}
          = t("btn.create")

app/views/leads/_popup_update_lead.html.haml
#popup-update-lead.modal.fade.custom-modal
  .modal-dialog.modal-500
    .modal-content
      .modal-header
        .title-row
          = t("leads.update")
      .modal-body
        = form_for(@lead, url: lead_path(params[:id]), method: :patch, remote: :true, html: {class: "custom-form", id: "form-update-lead"}) do
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-xs-12
              .form-group
                = label_tag :company_name, t("leads.company-name", required: "*")
                = text_field_tag :company_name, nil, class: "form-control", required: true, value: @lead.company_name
              .form-group
                = label_tag :contact_name, t("leads.contact-name")
                = text_field_tag :contact, nil, class: "form-control", value: @lead.contact_name
              .form-group
                = label_tag :phone_number, t("leads.phone")
                = text_field_tag :phone, nil, class: "form-control", pattern: "\\+?[\\s\\d]+", title: t("leads.phone-format"), value: @lead.phone
              .form-group
                = label_tag :email_address, t("leads.email")
                = select_tag :email, options_for_select(@lead.email, @lead.email), class: "form-control select2-tags", multiple: true
              .form-group.use-caret
                = label_tag :industry, t("leads.industry", required: "*")
                = select_tag :industry_id, options_for_select(@industry_lists, @industry_lists[2]), class: "form-control select2-option", required: true
              .form-group
                = label_tag :address, t("leads.address")
                = text_field_tag :address, nil, class: "form-control", value: @lead.address
              .form-group
                = label_tag :descriptions, t("leads.desc")
                = text_field_tag :descriptions, nil, class: "form-control", value: @lead.description
      .modal-footer
        %button.btn.btn-cancel.min-width-100(data-dismiss="modal")
          = t("btn.cancel")
        %button.btn.btn-green.min-width-100{form: "form-update-lead", type: "submit"}
          = t("btn.update")

app/views/leads/index.html.haml
.container.overflow-scroll
  .row.height-inherit-on-large.padding-top-15
    = render partial: "helpers/filter_box", locals: {choices: @leads_status_filter, search_url: search_leads_path, title: t("leads.index")}
    .col-xs-12.col-sm-9
      .text-right.margin-bottom-15
        %button.btn.btn-blue(data-toggle="modal" data-target="#popup-new-lead")
          = t("leads.new-btn")
      %table.table.target-form-result
        %thead
          %tr
            %th.sort-header(data-sort="desc" data-el="#search_sort")
              = t("leads.company-name-full", required: "").html_safe
            %th
              = t("leads.email-full").html_safe
            %th
              = t("leads.contact-full").html_safe
            %th
              = t("leads.status")
        %tbody
          %tr
            %td
              hello
            %td
              hello
            %td
              hello
            %td
              hello
    = render partial: "helpers/pagination", locals: {first_page: @first_page, last_page: @last_page}

= render partial: "popup_new_lead";

app/views/leads/show.html.haml
.container.overflow-scroll#scrolling
  .row.height-inherit-on-large.padding-top-15
    = render partial: "helpers/filter_box", locals: {choices: @leads_status_filter, search_url: search_leads_path, title: t("leads.index")}
    .col-xs-12.col-sm-9
      .row-header
        .row
          .col-xs-6.font-16.flex.align-items-center
            %span.glyphicon.glyphicon-menu-left.hover{onclick: "history.back();"}
            .title.margin-left-10
              = @lead.company_name
            .dropdown.flex.margin-left-10
              .box-grey.padding-0-10
                = @lead.status
              %button.margin-left-5.glyphicon.glyphicon-triangle-bottom.padding-0-3.dropdown-toggle.box-grey#change-lead-status(data-toggle="dropdown")
              %ul.dropdown-menu.dropdown-menu-right
                - @leads_status.each do |x|
                  %li
                    = link_to x[1], update_status_lead_path(params[:id], leads_status_id: x[0]), remote: :true, method: :post, class: "dropdown-item toggle-change-lead-status"
          .col-xs-6.text-right
            %button.btn.btn-green
              = t("leads.convert-client")
            .dropdown.custom.pull-right
              #dropdown-action.dropdown-toggle(data-toggle="dropdown")
                %span.glyphicon.glyphicon-option-horizontal
              %ul.dropdown-menu.dropdown-menu-right
                %li.dropdown-item
                  %a(data-toggle="modal" data-target="#popup-update-lead")
                    = t("btn.update")
                %li.dropdown-item
                  %a(data-toggle="modal" data-target="#popup-delete-lead")
                    = t("btn.delete")
        .row
          .col-xs-2
            .custom-thumbnail
              = @lead.company_name.to_s.split(" ").map(&:first).join("").upcase
          .col-xs-10
            %div
              = @lead.contact_name
            %div
              = @lead.phone
            %div
              = @lead.email
            %div
              Jasa
            %div
              Address
            %div
              Description
      .row.margin-top-50
        .col-xs-12.title.padding-bottom-10
          = t("activity.title")
          .pull-right.custom-plus-icon(data-toggle="modal" data-target="#popup-new-activity")
            +
        .col-xs-12
          %table.table
            %tbody.scroll-container
              = render partial: "activities/lists", locals: {lists: @query_results}
          .scroll-element.overflow-scroll(data-pagination-endpoint=activity_path data-pagination-pages="#{@total_pages}" data-current-page=1 colspan=3)
          .text-center.scroll-loading
            %span.glyphicon.glyphicon-repeat.glyphicon-refresh-animate

= render partial: "popup_update_lead";
= render partial: "activities/popup_new_activity"

= render partial: "helpers/popup_delete", locals: {popup_id: "popup-delete-lead",delete_url: lead_path(params[:id]), prompt_delete: t("leads.prompt-delete")}

- content_for :scripts do
  = javascript_include_tag "activity-list", "data-turbolinks-track" => true